name: Build with website(-new)^4

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Bogdanp/setup-racket@v1.11
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'CS'
          version: 'current'
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: jcs/package-lock.json
      - name: Install jcs dependencies
        shell: bash
        run: cd jcs && npm i
      - name: Actually run the build
        timeout-minutes: 1
        run: bash ./make.sh run_dist output-path="\"$RUNNER_TEMP/www.tgz\""
      - uses: actions/upload-artifact@v3
        with:
          name: 'github-pages'
          path: ${{ runner.temp }}/www.tgz
          retention-days: 1
          if-no-files-found: error
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
